# Generated by Django 3.2 on 2022-04-26 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('737ed039-2aec-4b90-8400-d07c2551d1c9')),
        ),
    ]
