# Generated by Django 3.2 on 2022-04-26 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi_calculated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('52efb289-0808-4cfe-9d2a-32f574f2a6b4')),
        ),
    ]
