# Generated by Django 3.2 on 2022-04-26 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220426_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6bc1861e-c3b4-4333-80ac-d21dc0805ad3'), unique=True),
        ),
    ]
