# Generated by Django 3.2 on 2022-04-26 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220426_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e24d17a3-a19f-4a3c-be94-665feeff3264'), unique=True),
        ),
    ]
