# Generated by Django 3.2 on 2022-04-27 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20220427_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2993654a-8dc9-4e5b-b407-a84bebf58a21'), unique=True),
        ),
    ]
